# Generated by Django 4.2.4 on 2024-01-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
