# Generated by Django 4.2.4 on 2024-01-17 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='likes',
            field=models.ManyToManyField(related_name='dweet_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
