# Generated by Django 4.2.4 on 2024-01-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0007_dweet_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
