# Generated by Django 4.2.4 on 2024-01-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0012_dweetcategory_dweet_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='dweetcategories', to='dwitter.dweetcategory'),
        ),
    ]
