# Generated by Django 4.2.4 on 2024-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0013_alter_dweet_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
