# Generated by Django 4.2.4 on 2024-01-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0015_alter_dweet_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
