# Generated by Django 4.2.4 on 2024-01-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0017_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
    ]
