# Generated by Django 4.2.4 on 2024-01-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0018_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
