# Generated by Django 4.2.4 on 2024-01-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0019_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
